# Editor completions
"$schema" = "https://starship.rs/config-schema.json"

# Prompt configuration
format = '[](purple) [kathy](blue italic) [󰣐 ](purple) [](blue)$directory[](blue) $character'

right_format = """
$localip\
$shlvl\
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell"""

[character]
success_symbol = '[❯](purple)'

# Modules
[cmd_duration]
format = '[$duration]($style)'

[cmake]
symbol = '[󱨊](blue)[󱨊](green)[󱨊](red) '
format = '$symbol'

[c]
format = '[$symbol($version ($name))]($style) '
version_format = "v${raw}"
symbol = " "
style = "blue"
commands = [['clang','--version'],['gcc','--version'],['cc','--version']]

[lua]
format = '[$symbol]($style)' 
symbol = ' '
style = 'bold blue'

[kotlin]
format = '[$symbol]($style) '
symbol = ' '
style = 'bright-purple'

[java]
format = '[$symbol]($style) '
symbol = ' '
style = 'red'

[zig]
format = "[$symbol]($style) "
symbol = " "
style = "yellow"

[gradle]
format = '[$symbol]($style) '
symbol = ' '
style = 'cyan'

[python]
format = '[$symbol]($style) '
symbol = ' '
style = 'yellow'

[rust]
format = '[$symbol]($style) '
symbol = ' '
style = 'bold red'

[nodejs]
format = '[$symbol]($style)'

[directory]
format = '[ $path ](bg:blue fg:black)[$read_only]($read_only_style)'

[package]
format = ""
symbol = " "

# Git modules
[git_branch]
format = '[$symbol $branch(:$remote_branch)]($style) '
symbol = '󰊢 '

