#! /bin/sh

# Important

pgrep -x sxhkd > /dev/null || sxhkd &

# Stating programs

pgrep -x trayer > /dev/null || exec trayer --edge bottom --align right --height 15 --SetDockType true --transparent true --alpha 256 --margin 15 &
pgrep -x eww &> /dev/null || eww open bar &> /dev/null &
xdo lower -N eww-bar
xdo lower -N eww-bar
xdo lower -N eww-bar
pgrep -x copyq > /dev/null || exec copyq session > /dev/null &copyq hide &
pgrep -x emote > /dev/null || exec emote > /dev/null &
pgrep -x picom > /dev/null || exec picom --experimental-backends &
feh --bg-fill '/home/Kathy/Pictures/moon-clouds-4k.png' &
pgrep -x pipewire > /dev/null || /usr/bin/pipewire &
pgrep -x pipewire-pulse > /dev/null || /usr/bin/pipewire-pulse &
pgrep -x wireplumber > /dev/null || /usr/bin/wireplumber &

## bspc rules

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         0
bspc config window_gap           0
bspc config border_width         1

# Padding
bspc config bottom_padding 15
bspc config right_padding 5
bspc config left_padding 5
bspc config top_padding 55

bspc config normal_border_color "#ea9a97"
bspc config active_border_color "#f6c177"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a stalonetray manage=on state=floating

# custom rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a librewolf:Toolkit sticky=on state=floating
bspc rule -a LibreWolf:Toolkit sticky=on state=floating
bspc rule -a copyq state=floating
bspc rule -a jetbrains-idea:Welcome\ to\ IntelliJ\ IDEA state=floating
bspc rule -a obs state=floating
bspc rule -a LibreWolf:Toolkit sticky=on state=floating

# Temporary fix for a web-greeter bug
# https://github.com/JezerM/web-greeter/issues/80
sudo pkill python3
