#! /bin/sh

# Killing programs

pkill dunst
pkill eww
pkill emote
pkill copyq
pkill ew
pkill picom
pkill trayer

# Important

pgrep -x sxhkd > /dev/null || sxhkd &

# Stating programs
exec trayer --edge bottom --align right --height 15 --width 15 --SetDockType true --transparent true --widthtype request --alpha 256 --margin 15 &
eww open bar > /dev/null &
xdo lower -N eww-bar
xdo lower -N eww-bar
xdo lower -N eww-bar
exec copyq session > /dev/null &
copyq hide &
exec emote > /dev/null &
picom --experimental-backends &
feh --bg-scale '/home/Katie/Pictures/wallpaper-pixel-clouds.png' &
## bspc rules

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         0
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a stalonetray manage=on state=floating


# custom rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a librewolf:Toolkit sticky=on state=floating
bspc rule -a LibreWolf:Toolkit sticky=on state=floating
bpsc rule -a prismlauncher state=floating
bspc rule -a copyq state=floating
bspc rule -a jetbrains-idea:Welcome\ to\ IntelliJ\ IDEA state=floating
bspc rule -a obs state=floating
bscp rule -a LibreWolf:Toolkit sticky=on state=floating
