Diagnostics:
  UnusedIncludes: Strict
  ClangTidy:
    Add: 
      - modernize*
      - bugprone*
      - cert-dcl50-cpp
      - cert-dcl58-cpp
      - cert-err33-c
      - cert-err34-c
      - cert-err52-cpp
      - cert-err58-cpp
      - cert-err60-cpp
      - cert-flp30-c
      - cert-mem57-cpp
      - cert-msc51-cpp
      - cert-oop57-cpp
      - cert-oop58-cpp
      - concurrency-*
      - cppcoreguidelines-*
      - llvm-header-guard
      - llvm-include-order
      - llvm-namespace-comment
      - llvm-prefer-isa-or-dyn-cast-in-conditionals
      - llvm-prefer-register-over-unsigned
      - misc-confusable-identifiers
      - misc-const-correctness
      - misc-definitions-in-headers
      - misc-new-delete-overloads
      - misc-non-copyable-objects
      - misc-non-private-member-variables-in-classes
      - misc-redundant-expression
      - misc-static-assert
      - misc-throw-by-value-catch-by-reference
      - misc-unconventional-assign-operator
      - misc-uniqueptr-reset-release
      - misc-unused-alias-decls
      - misc-unused-parameters
      - misc-unused-using-decls
      - misc-use-anonymous-namespace
      - performance-faster-string-find
      - performance-for-range-copy
      - performance-implicit-conversion-in-loop
      - performance-inefficient-algorithm
      - performance-inefficient-string-concatenation
      - performance-inefficient-vector-operation
      - performance-move-const-arg
      - performance-move-constructor-init
      - performance-no-int-to-ptr
      - performance-noexcept-move-constructor
      - performance-trivially-destructible
      - performance-type-promotion-in-math-fn
      - performance-unnecessary-copy-initialization
      - performance-unnecessary-value-param
      - portability-std-allocator-const
      - readability-avoid-const-params-in-decls
      - readability-const-return-type
      - readability-container-contains
      - readability-container-data-pointer
      - readability-container-size-empty
      - readability-delete-null-pointer
      - readability-duplicate-include
      - readability-else-after-return
      - readability-function-cognitive-complexity
      - readability-function-size
      - readability-implicit-bool-conversion
      - readability-inconsistent-declaration-parameter-name
      - readability-isolate-declaration
      - readability-magic-numbers
      - readability-make-member-function-const
      - readability-misleading-indentation
      - readability-misplaced-array-index
      - readability-named-parameter
      - readability-non-const-parameter
      - readability-qualified-auto
      - readability-redundant-access-specifiers
      - readability-redundant-control-flow
      - readability-redundant-declaration
      - readability-redundant-function-ptr-dereference
      - readability-redundant-member-init
      - readability-redundant-preprocessor
      - readability-redundant-smartptr-get
      - readability-redundant-string-cstr
      - readability-redundant-string-init
      - readability-simplify-boolean-expr
      - readability-simplify-subscript-expr
      - readability-static-accessed-through-instance
      - readability-static-definition-in-anonymous-namespace
      - readability-string-compare
      - readability-suspicious-call-argument
      - readability-uniqueptr-delete-release
      - readability-uppercase-literal-suffix
      - readability-use-anyofallof
    CheckOptions: 
      readability-identifier-naming.VariableCase: camelBack
      readability-identifier-naming.AbstractClassCase: CamelCase
      readability-identifier-naming.ClassCase: CamelCase
      readability-identifier-naming.ClassConstantCase: CamelCase
      readability-identifier-naming.MemberCase: camelBack
      readability-identifier-naming.MemberPrefix: "m_"
      readability-identifier-naming.MethodCase: camelBack
      readability-identifier-naming.ConstantCase: camelBack
      readability-identifier-naming.ConstantMemberCase: camelBack
      readability-identifier-naming.ConstantParameterCase: camelBack
      readability-identifier-naming.ConstantPointerParameterCase: camelBack
      readability-identifier-naming.ConstexprFunctionCase: CameCase
      readability-identifier-naming.ConstexprMethodCase: camelBack
      readability-identifier-naming.ConstexprVariableCase: CamelCase
      readability-identifier-naming.EnumCase: CamelCase
      readability-identifier-naming.EnumConstantCase: CamelCase
      readability-identifier-naming.FunctionCase: CamelCase
      readability-identifier-naming.GlobalConstantCase: CamelCase
      readability-identifier-naming.GlobalConstantPrefix: "g_"
      readability-identifier-naming.GlobalFunctionCase: CamelCase
      readability-identifier-naming.GlobalPointerCase: CamelCase
      readability-identifier-naming.GlobalPointerPrefix: "g_"
      readability-identifier-naming.GlobalVariableCase: camelBack
      readability-identifier-naming.GlobalVariablePrefix: "g_"
      readability-identifier-naming.LocalVariableCase: camelBack
      readability-identifier-naming.NamespaceCase: CamelCase
      readability-identifier-naming.ParamterCase: camelBack
      readability-identifier-naming.StructCase: CamelCase
      readability-identifier-naming.TypeAliasCase: CamelCase
      readability-identifier-naming.TypedefCase: CamelCase
